name: CI

on: push

jobs:
  test:
    name: Node.js v${{ matrix.nodejs }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nodejs: [14, 16, 18]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.nodejs }}
    - uses: pnpm/action-setup@v2.2.4
      with:
        version: 5
        run_install: false

    - name: (env) cache
      uses: actions/cache@v2
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-${{ matrix.nodejs }}-${{ hashFiles('**/package.json') }}
        restore-keys: ${{ runner.os }}-${{ matrix.nodejs }}-

    - name: Install
      run: pnpm install

    # - name: Type Checks
    #   run: pnpm run types

    - name: Compiles
      run: pnpm run build

    - name: Tests
      if: matrix.nodejs < 18
      run: pnpm run test

    - name: Tests w/ Coverage
      if: matrix.nodejs >= 18
      run: |
        pnpm add -g c8
        c8 --include=packages pnpm test

    - name: Report Coverage
      if: matrix.nodejs >= 18
      run: |
        c8 report --reporter=text-lcov > coverage.lcov
        bash <(curl -s https://codecov.io/bash)
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
