name: CI

on: push

jobs:
  test:
    name: Node.js v${{ matrix.nodejs }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nodejs: [14, 16]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.nodejs }}

    - name: (env) pnpm
      run: curl -L https://pnpm.js.org/pnpm.js | node - add --global pnpm

    - name: (env) cache
      uses: actions/cache@v2
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-${{ matrix.nodejs }}-${{ hashFiles('**/package.json') }}
        restore-keys: ${{ runner.os }}-${{ matrix.nodejs }}-

    - name: Install
      run: pnpm install

    - name: Type Checks
      run: pnpm run types

    - name: Compiles
      run: pnpm run build

    - name: Tests
      if: matrix.nodejs < 16
      run: pnpm run test

    - name: Tests w/ Coverage
      if: matrix.nodejs >= 16
      run: |
        pnpm add -g c8
        c8 --include=packages pnpm test

    - name: Report Coverage
      if: matrix.nodejs >= 16
      run: |
        c8 report --reporter=text-lcov > coverage.lcov
        bash <(curl -s https://codecov.io/bash)
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
